# Generated by Django 4.0.3 on 2022-04-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_Creacion_Tabla_Tareas_y_Relaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='tareas',
            name='descripcion',
            field=models.TextField(default='nada'),
            preserve_default=False,
        ),
    ]
