# Generated by Django 4.0.3 on 2022-04-15 01:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_Creacion_Tabla_Platos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='foto',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
